"""Fictional fixtures. Prewritten analyses are explicitly marked as sample data."""
ROWS=[
('John Parker','Brightside Co.','Pricing for support automation','Sales','High','Positive',True,'We are looking to automate customer support intake this month. Could you share pricing and availability?','Potential customer requests pricing and availability for support automation.'),
('Sarah Lee','Cedar Design','Our team cannot sign in','Support','High','Negative',True,'All five team members receive an access denied error after signing in. Our client deadline is today. Can you help us restore access?','An access issue blocks a five-person team with a deadline today.'),
('Morgan Patel','Ledger Payments','Payment receipt — September','Billing','Low','Neutral',False,'Your September subscription payment of $49 has been received. This receipt is for your records. No action is needed.','September subscription payment receipt; no action requested.'),
('Amelia Brooks','Luma Studio','Could we see a product demo?','Sales','Medium','Positive',True,'We are exploring tools for our operations team. Could you walk us through a demo next week?','Prospective customer asks for a product demonstration next week.'),
('Theo Wilson','Northstar Studio','Agenda for our planning meeting','Internal','Low','Neutral',False,'Sharing the agenda for Thursday: onboarding review, support trends and next sprint priorities. No preparation is required.','Internal planning agenda shared for information.'),
('Elena Ruiz','Harbor Retail','Charged twice for the same invoice','Billing','High','Negative',True,'Invoice INV-2041 appears twice on our bank statement. Please investigate the duplicate charge and explain the next steps.','Customer reports a possible duplicate invoice charge and requests investigation.'),
('Daniel Kim','Aster Works','Export includes empty columns','Support','Medium','Neutral',True,'When I export the weekly report, the CSV includes three empty columns. Is there a setting I should change?','Customer asks how to remove empty columns from report exports.'),
('Olivia Reed','Weekly Brief','Your weekly industry digest','Other','Low','Neutral',False,'This week: new collaboration tools, remote work research and upcoming events. You are receiving our weekly newsletter.','Industry newsletter; no response required.'),
('Noah Evans','Northstar Studio','Review the onboarding checklist','Internal','Medium','Neutral',True,'Could you review the attached onboarding checklist before Friday? I need your feedback on the account handover section.','Colleague requests review of an onboarding checklist by Friday.'),
('Sofia Costa','Maple Partners','Integration with our CRM','Sales','High','Positive',True,'We have budget approved for lead automation. Can your team connect our website forms to our CRM and prepare follow-up drafts?','Budget-approved lead seeks CRM and website form automation.'),
('Ethan Cole','Bluebird Cafe','Thank you for your help','Support','Low','Positive',False,'The login problem is resolved now. Thank you for the quick assistance. Nothing else is needed from your team.','Customer confirms the login issue is resolved and thanks the team.'),
('Mia Laurent','Pine Consulting','Please update our billing address','Billing','Medium','Neutral',True,'Please let me know how to update the billing address for future invoices. We have moved offices and want to keep our records current.','Customer asks for the process to update a billing address.'),
('Lucas Grant','Northstar Studio','Security review needed today','Internal','High','Neutral',True,'Please review the access list today. A departing contractor still appears in the project workspace. Confirm who should handle the removal.','Internal access review is needed for a departing contractor.'),
('Ava Martin','Summit Labs','Partnership introduction','Sales','Medium','Positive',True,'We build analytics tools for small businesses and would like to explore a referral partnership. Who is the right person to speak with?','Potential partner asks for a referral partnership contact.'),
('Promo Desk','Unknown Sender','You have been selected for a prize','Other','Low','Neutral',False,'Claim your unexpected prize now by sharing your payment details. This unsolicited promotion has no connection to your account.','Unsolicited prize promotion requests payment details; do not reply.')]

def samples():
    for i,(name,company,subject,category,priority,sentiment,action,body,summary) in enumerate(ROWS):
        yield {'message_id':f'demo-{i+1:02}','thread_id':'','sender':name,'sender_email':name.lower().replace(' ','.')+'@example.com','subject':subject,'body':body,'received_at':f'2026-09-08T{15-i//4:02}:{55-(i%4)*12:02}:00Z'}, {'category':category,'priority':priority,'sentiment':sentiment,'summary':summary,'action_required':action,'suggested_reply':f'Hi {name.split()[0]},\n\nThank you for getting in touch. We have received your request about {subject.lower()}. Could you share the relevant details so our team can review the next step?\n\nBest,\nNorthstar Studio' if action else ''}
