import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Inbox,Mail,Flag,FileText,Settings,Workflow,Search,ArrowUpRight,ArrowRight,Check,ShieldCheck,X,ChevronRight,RefreshCw,CheckCheck,Plus,SendHorizontal,Command,Clock,Download,AlertCircle}from'lucide-react';
import './style.css';

async function api(path,body){const r=await fetch('/api'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'Please check the supplied values.');return d;}
const navs=[['Inbox',Inbox],['Needs Reply',Mail],['High Priority',Flag],['Drafts',FileText],['Automation',Workflow],['Settings',Settings]];
const initials=n=>n.split(' ').map(x=>x[0]).slice(0,2).join('');
const time=t=>new Date(t).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
function Badge({children,type=''}){return <span className={'badge '+type}>{children}</span>}
function App(){
 const[rows,setRows]=useState([]),[page,setPage]=useState('Inbox'),[search,setSearch]=useState(''),[cat,setCat]=useState('All categories'),[config,setConfig]=useState({}),[selected,setSelected]=useState(null),[draft,setDraft]=useState(''),[events,setEvents]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[showTest,setShowTest]=useState(false);
 async function refresh(){const [r,c]=await Promise.all([api('/emails'),api('/config')]);setRows(r);setConfig(c);}
 useEffect(()=>{refresh().catch(e=>setError(e.message));const timer=setInterval(()=>refresh().catch(()=>{}),8000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{function escape(e){if(e.key==='Escape'&&!busy)close()}window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[selected,draft,busy]);
 async function open(r){setError('');setSelected(r);setDraft(r.draft);setEvents([]);try{setEvents(await api(`/emails/${r.id}/events`))}catch(e){setError(e.message)}}
 function close(){if(busy)return;if(selected&&draft!==selected.draft&&!confirm('Discard unsaved draft changes?'))return;setSelected(null);setShowTest(false);setError('')}
 async function run(fn){setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function review(action){await run(async()=>{const r=await api(`/emails/${selected.id}/review`,{revision:selected.revision,draft,action});await open(r);await refresh();setNotice(action==='approve'?'Approved for human review. No email was sent.':action==='complete'?'Email marked complete.':'Local draft saved.');})}
 const analyzed=rows.filter(r=>r.analysis),high=analyzed.filter(r=>r.analysis.priority==='High'),needs=analyzed.filter(r=>r.analysis.action_required&&r.status!=='Complete'),drafts=rows.filter(r=>r.draft&&r.status!=='Complete');
 const filtered=rows.filter(r=>{const a=r.analysis;return(page!=='Needs Reply'||(a?.action_required&&r.status!=='Complete'))&&(page!=='High Priority'||a?.priority==='High')&&(page!=='Drafts'||(r.draft&&r.status!=='Complete'))&&(cat==='All categories'||a?.category===cat)&&[r.original.sender,r.original.subject,a?.summary].join(' ').toLowerCase().includes(search.toLowerCase())});
 return <div className="shell"><aside><a className="brand" href="/"><span className="brandmark"><SendHorizontal size={22}/></span>MailPilot<span className="beta">BETA</span></a><div className="workspace"><div className="workspaceIcon">N</div><div><strong>Northstar Studio</strong><small>Personal demo workspace</small></div><ChevronRight size={14}/></div><p className="navLabel">WORKSPACE</p><nav>{navs.map(([n,Icon],i)=><button key={n} onClick={()=>{setPage(n);setSearch('');setError('')}} className={(page===n?'active ':'')+(i===4?'separated':'')}><Icon size={18}/>{n}{n==='Inbox'&&<span className="navCount">{rows.length}</span>}{n==='High Priority'&&high.length>0&&<i className="navDot"/>}</button>)}</nav><div className="humanNote"><ShieldCheck size={19}/><strong>You're the final checkpoint.</strong><p>MailPilot prepares replies.<br/>You decide what gets sent.</p></div><div className="profile"><span className="avatar">YN</span><div><strong>Yunis Nasibov</strong><small>Workspace owner</small></div></div></aside>
 <main><header><div className="breadcrumb">Workspace <ChevronRight size={13}/><b>{page}</b></div><div className="headerRight"><span className="liveDot"/>Local workspace<span className="divider"/><span className="avatar small">YN</span></div></header>
 <div className="content"><div className="pageHead"><div><span className="eyebrow">MAILPILOT / OPERATIONS</span><h1>{page==='Automation'?'A clear path for every email.':page==='Settings'?'Your connections, in one place.':'AI Email Operations'}</h1><p>{page==='Automation'?'From incoming message to a reply ready for review.':page==='Settings'?'Connect only what your workflow needs.':'Inbox automated. Decisions stay human.'}</p></div><div className="headButtons"><button className="button" disabled={busy} onClick={()=>run(async()=>{await api('/demo/seed',{});await refresh();setNotice('15 fictional examples loaded. Existing edits preserved.')})}><Plus size={16}/>Sample inbox</button><button className="button primary" onClick={()=>{setShowTest(true);setError('')}}><span className="spark">✧</span>Try AI analysis</button></div></div>
 {error&&!selected&&!showTest&&<div className="error" role="alert"><AlertCircle size={17}/>{error}</div>}
 {page==='Settings'?<div className="settingsGrid"><section className="panel"><div className="panelHeading"><h2>Connections</h2><Badge>Local setup</Badge></div>{[['Gemini AI',config.gemini_configured?'Key configured':'Not connected',config.gemini_configured?'Run a fictional test to verify your account.':'Configure your Gemini key in the local .env file.'],['Gmail',config.gmail_drafts_verified?'Draft creation verified':'Awaiting connection',config.gmail_drafts_verified?`${config.gmail_drafts_verified} real draft receipts recorded.`:'Connect a test Gmail account in the n8n workflow.'],['n8n intake',config.intake_configured?'Token configured':'Not configured','Use the MailPilot workflow and its own Header Auth credential.'],['Google Sheets','Optional','SQLite is the default record store. Sheets is not connected.']].map(([name,status,note])=><div className="connection" key={name}><div className="connectionTitle"><strong>{name}</strong><Badge type={status.includes('verified')?'approved':''}>{status}</Badge></div><p>{note}</p></div>)}</section><section className="panel guide"><ShieldCheck size={30}/><h2>Review comes before sending.</h2><p>There is no send-email operation in MailPilot. Approval records a decision in this workspace.</p><p>Edits made here are saved locally. If a Gmail draft already exists, copy your final text to Gmail before sending it yourself.</p><p>Sample emails use prewritten analyses. Live tests are identified separately. Your email contents are sent to Gemini only when analysis runs.</p></section></div>:
 page==='Automation'?<><div className="workflowBanner"><Badge type="approved">HUMAN REVIEW REQUIRED</Badge><h2>Organized automatically.<br/>Sent only by you.</h2><p>One incoming email. One structured analysis. A draft your team can actually review.</p></div><div className="workflowSteps">{[['01','Gmail','A new MailPilot-Test email arrives',Mail],['02','n8n','The message is normalized',Workflow],['03','Gemini AI','Category, priority and summary',Command],['04','Save & draft','SQLite record and Gmail draft',FileText],['05','Human review','Read, edit and approve locally',ShieldCheck]].map(([n,title,desc,Icon])=><div className="step" key={n}><span>{n}</span><Icon size={24}/><h3>{title}</h3><p>{desc}</p></div>)}</div><div className="twoCol"><section className="panel guide"><h2>Built for the real inbox</h2><p>Repeated Gmail message IDs reuse the existing analysis. Draft creation is reserved once, so retries cannot silently create more drafts.</p><p>If a provider fails, the email is retained with a retry status. Ambiguous Gmail creation failures require inspection in Gmail and n8n.</p></section><section className="panel guide"><h2>What's connected?</h2><p>Gemini: {config.gemini_configured?'configured':'not configured'} · Gmail draft receipts: {config.gmail_drafts_verified||0}</p><p>The demo is complete only after a test email reaches Gmail and creates a real draft. The sample inbox demonstrates the interface without connecting an account.</p><button className="textButton" onClick={()=>setPage('Settings')}>View connection status <ArrowRight size={16}/></button></section></div></>:
 <><div className="metrics">{[['Emails processed',analyzed.length,Inbox,'Analyzed and organized'],['High priority',high.length,Flag,'Worth your attention'],['Needs reply',needs.length,Mail,'Waiting for a decision'],['Drafts created',drafts.length,FileText,'Local drafts ready for review']].map(([label,count,Icon,sub],i)=><section className="metric" key={label}><div><span>{label}</span><Icon size={17}/></div><strong className={i===1?'warm':''}>{count.toString().padStart(2,'0')}</strong><small>{sub}</small></section>)}</div>
 <div className="reviewStrip"><span className="stripIcon"><ShieldCheck size={18}/></span><b>Automation with a human touch.</b><span>Every suggested reply stays a draft until you take over.</span><button onClick={()=>setPage('Automation')}>View workflow <ArrowUpRight size={15}/></button></div>
 <section className="panel inboxPanel"><div className="panelHeading"><div className="tableTitle"><h2>{page==='Inbox'?'Your inbox':page}</h2><Badge>{filtered.length}</Badge></div><div className="tableActions"><span className="sampleLabel">{rows.every(r=>r.source==='Sample')?'FICTIONAL SAMPLE DATA':'SAMPLE & CONNECTED EMAILS'}</span><button aria-label="Refresh inbox" className="iconButton" onClick={()=>run(refresh)}><RefreshCw size={16}/></button><a href="/api/export" className="iconButton" aria-label="Export CSV"><Download size={16}/></a></div></div><div className="filters"><div className="search"><Search size={17}/><input placeholder="Search sender, subject or summary…" aria-label="Search emails" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>/</kbd></div><select aria-label="Filter category" value={cat} onChange={e=>setCat(e.target.value)}>{['All categories','Sales','Support','Billing','Internal','Other'].map(c=><option key={c}>{c}</option>)}</select></div>
 <div className="tableScroll"><table><thead><tr><th>SENDER / SUBJECT</th><th>CATEGORY</th><th>PRIORITY</th><th>AI SUMMARY</th><th>STATUS</th><th/></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><button className="emailOpen" onClick={()=>open(r)}><span className={'senderAvatar '+(r.analysis?.category||'')}>{initials(r.original.sender)}</span><span><b>{r.original.sender}</b><small>{r.original.subject}</small></span></button></td><td><Badge type={r.analysis?.category?.toLowerCase()}>{r.analysis?.category||'Pending'}</Badge></td><td><span className={'priority '+r.analysis?.priority}><i/>{r.analysis?.priority||'—'}</span></td><td className="summary"><span>{r.analysis?.summary||r.error||'Waiting for analysis'}</span></td><td><span className={'status '+r.status.replaceAll(' ','').toLowerCase()}>{r.status==='Approved'?<CheckCheck size={13}/>:r.draft?<FileText size={13}/>:<Check size={13}/>} {r.status}</span></td><td><button className="iconButton" aria-label={'Open '+r.original.sender} onClick={()=>open(r)}><ChevronRight size={16}/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><Inbox size={34}/><h3>{rows.length?'No matching emails':'A calmer inbox starts here.'}</h3><p>{rows.length?'Try another search or category.':'Load 15 fictional emails, or connect a test account in Settings.'}</p></div>}</div><div className="tableFooter"><span>{filtered.length} email{filtered.length!==1?'s':''} in this view</span><span><span className="liveDot"/>Refreshes every 8 seconds</span></div></section></>}
 <footer>MailPilot <span>Built by Yunis Nasibov</span><span className="footerRight"><ShieldCheck size={13}/>No automatic sending. Ever.</span></footer></div></main>
 {selected&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="detail" role="dialog" aria-modal="true" aria-labelledby="detailTitle"><div className="detailHeader"><span><Mail size={18}/> EMAIL REVIEW</span><button aria-label="Close email" className="iconButton" onClick={close} disabled={busy}><X size={21}/></button></div><div className="detailBody"><div className="detailSubject"><div><Badge type={selected.source==='Sample'?'':'approved'}>{selected.source==='Sample'?'Sample · prewritten analysis':selected.source}</Badge><h2 id="detailTitle">{selected.original.subject}</h2></div><Badge>{selected.status}</Badge></div><section className="original"><div className="senderLine"><span className="senderAvatar">{initials(selected.original.sender)}</span><div><b>{selected.original.sender}</b><small>{selected.original.sender_email}</small></div><time>{time(selected.original.received_at||selected.created)}</time></div><p>{selected.original.body}</p></section>
 {selected.analysis?<section className="analysisBox"><div className="sectionTitle"><h3><span className="spark">✧</span> AI analysis</h3><Badge>{selected.source==='Sample'?'Example':'Gemini'}</Badge></div><div className="analysisFacts"><div><small>Category</small><Badge type={selected.analysis.category.toLowerCase()}>{selected.analysis.category}</Badge></div><div><small>Priority</small><span className={'priority '+selected.analysis.priority}><i/>{selected.analysis.priority}</span></div><div><small>Sentiment</small><b>{selected.analysis.sentiment}</b></div><div><small>Action required</small><b>{selected.analysis.action_required?'Yes':'No'}</b></div></div><p>{selected.analysis.summary}</p></section>:<div className="error"><AlertCircle size={18}/><div>{selected.error||'Awaiting analysis'}<button className="button" disabled={busy} onClick={()=>run(async()=>{await open(await api(`/emails/${selected.id}/retry`,{}));await refresh()})}>Retry analysis</button></div></div>}
 {selected.analysis&&<section className="replyBox"><div className="sectionTitle"><h3><FileText size={18}/>Suggested reply</h3><span className="muted">Editable · never auto-sent</span></div>{selected.analysis.action_required||draft?<textarea aria-label="Suggested reply" value={draft} disabled={busy} onChange={e=>setDraft(e.target.value)} maxLength={5000}/>:<p className="noAction"><CheckCheck size={18}/>No reply needed for this email.</p>}{selected.gmail_draft_id&&<p className="gmailReceipt"><CheckCheck size={15}/>Gmail draft created. Local edits are not automatically synced to Gmail.</p>}<div className="reviewActions"><button className="button" disabled={busy||draft===selected.draft} onClick={()=>review('save')}>Save edits</button><button className="button primary" disabled={busy||!draft.trim()} onClick={()=>review('approve')}><Check size={16}/>Approve draft</button><button className="textButton" disabled={busy} onClick={()=>review('complete')}>Mark complete</button></div><small className="approvalNote"><ShieldCheck size={13}/>Approval is recorded here. Send manually from Gmail after your final check.</small></section>}
 {error&&<div className="error" role="alert">{error}</div>}<section className="activity"><h3>Activity</h3>{events.map((e,i)=><div key={i}><i/><p>{e.action}<small>{time(e.created)}</small></p></div>)}</section></div></section></div>}
 {showTest&&<div className="overlay"><section className="testDialog" role="dialog" aria-modal="true" aria-labelledby="testTitle"><div className="detailHeader"><span>LIVE GEMINI TEST</span><button className="iconButton" aria-label="Close test" disabled={busy} onClick={close}><X/></button></div><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const r=await api('/demo/analyze',{message_id:crypto.randomUUID(),sender:f.get('sender'),sender_email:'demo@example.com',subject:f.get('subject'),body:f.get('body')});setShowTest(false);await refresh();await open(r)})}}><h2 id="testTitle">Give your inbox a test run.</h2><p>This sends a fictional email to Gemini and saves a local result. It does not create a Gmail draft.</p><label>Sender<input name="sender" defaultValue="John Parker" required maxLength={150}/></label><label>Subject<input name="subject" defaultValue="Need pricing for automation" required maxLength={500}/></label><label>Email<textarea name="body" defaultValue="Hi, we're looking to automate our customer support workflow this month. Could you share pricing and availability? We receive around 40 inquiries per week and need reply drafts for our team to review." required maxLength={18000}/></label>{error&&<div className="error" role="alert">{error}</div>}<button className="button primary" disabled={busy||!config.gemini_configured}>{busy?<><RefreshCw className="spin" size={17}/>Analyzing email…</>:<>Analyze with Gemini <ArrowRight size={17}/></>}</button></form></section></div>}
 {notice&&<div className="toast" role="status"><CheckCheck size={18}/>{notice}</div>}</div>
}
createRoot(document.getElementById('root')).render(<App/>);
